### PR TITLE
Feed disclaimer

### LINKED ISSUE #330: Revert to old feed names
To do:
 - Revert to the old naming convention to feed names that does not use abbreviations. 
 - Add a disclaimer below the feeds to explain what the feeds contain

### PR DESCRIPTION
**Pull request by ehunter-usgs**
fixes #330

### CODE REVIEW

**Comment by llastowka-usgs** [comment]
What we want to do is  to capture that the feeds include more than the US earthquakes.  We could clean up the previous implementation to be more consistent in using Mags and M and reduce the use of special characters or rethink how to describe the lists.  I was thinking we could have something at the top that says something like "All lists include events outside the US that are nominally Magnitude 4.5 or greater.  LINK to the page that explains that.."

**Comment by ehunter-usgs** [comment]
Now it looks like this:
screen shot 2017-01-05 at 3 21 18 pm

**Comment by llastowka-usgs** [comment]
This makes sense to me, the disclaimer covers our worldwide events and what changes in the feeds is the U.S. subsets so that is what is labeled.

**Comment by jmfee-usgs** [comment]
Seems to suggest we include some events less than 4.5 worldwide.  What about

`Most <link>earthquakes below M4.5 outside the US are not reported by USGS</link>.`

**Comment by ehunter-usgs** [comment]
**Jeremy's wording:**
`Not all earthquakes are reported by USGS below M2.5 in the US, and below M4.5 outside the US, read more`

Possible variations?
- Not all earthquakes below M2.5 in the US, and below M4.5 outside the US, are reported by the USGS.
- Not all earthquakes in the US (below M2.5) and outside the US (below M4.5) are reported by the USGS.
- Not all earthquakes are reported by the USGS.

**Pull request merged**
